package com.main.hackatonjr;

import java.util.ArrayList;

enum SortMode {
    PRICE_ASCENDING,
    PRICE_DESCENDING,
    NAME_ALPHABETICAL,
    NAME_REVERSE_ALPHABETICAL
}

public class Shop {
    private ArrayList<Stockable> stock;
    private ArrayList<Stockable> cart;
    private int lastId;//Contains the id of the last created stockable in order to manage new stockables generated by the random capsules

    public Shop(){
        this.stock = new ArrayList<>();
        this.stock.add(new Capsule(0, "Blue capsule (Gears)",500.0f, CapsuleColor.BLUE));
        this.stock.add(new Capsule(1, "Red capsule (Vehicles)", 3000.0f, CapsuleColor.RED));
        this.stock.add(new Capsule(2, "Green capsule (Foods)", 500.0f, CapsuleColor.GREEN));

        Catalog catalog = new Catalog();
        this.stock.addAll(catalog.gears);
        this.stock.addAll(catalog.vehicles);
        this.stock.addAll(catalog.foods);
        this.cart = new ArrayList<>();
        this.lastId = this.stock.size()+1;
    }

    public ArrayList<Stockable> getStock(){
        return this.stock;
    }
    public ArrayList<Stockable> getCart(){
        return this.cart;
    }
    public int getLastId(){
        return this.lastId;
    }

    public void addToCart(Stockable stockable){
        this.cart.add(stockable);
    }

    public float getCartPrice(){
        float price = 0;
        for(Stockable stockable : cart) {
            price += stockable.getPrice();
        }
        return price;
    }

    public void emptyCart(){
        this.cart = new ArrayList<Stockable>();
    }

    //Returns true if the user could buy the stockable from the shop or false if he couldn't
    public boolean buyOneStockable(User user, Stockable stockable){
        float price = stockable.getPrice();
        if(stockable.getPrice() > user.getMoney()){//The user can't buy the stockable
            return false;
        }
        
        user.withdrawMoney(price);
        
        if(stockable instanceof Capsule) {
            Capsule capsule = (Capsule)stockable;
            Stockable random = capsule.getRandomObject(this.lastId);
            user.addToInventory(random);
            this.lastId++;
        }
        else{
            user.addToInventory(stockable);
            this.stock.remove(stockable);
        }
        return true;
    }

    public boolean buyCartStockables(User user){
        ArrayList<Stockable> copy = new ArrayList<>(cart);

        if(this.getCartPrice() > user.getMoney()){
            this.emptyCart();
            return false;
        }
        
        for(Stockable stockable : copy) {
            if(this.buyOneStockable(user,stockable) == false){
                this.emptyCart();
                return false;
            }
        }
        this.emptyCart();
        return true;
    }

    public void sortStock(SortMode mode){
        int i = 0, j = 0, size = this.stock.size();
        
        //Bubble sort
        for(i=0;i<size-1;i++){
            for(j=0;j<size-i-1;j++){
                boolean swap = false;
                Stockable current = this.stock.get(j);
                Stockable next = this.stock.get(j+1);
                
                switch(mode) {
                    case PRICE_ASCENDING:
                        swap = current.getPrice() > next.getPrice();
                        break;

                    case PRICE_DESCENDING:
                        swap = current.getPrice() < next.getPrice();
                        break;

                    case NAME_ALPHABETICAL:
                        swap = current.getName().compareTo(next.getName()) > 0;
                        break;

                    case NAME_REVERSE_ALPHABETICAL:
                        swap = current.getName().compareTo(next.getName()) < 0;
                        break;
                }
                
                if (swap) {
                    this.stock.set(j, next);
                    this.stock.set(j+1, current);
                }
            }
        }
    }
}
